version: '2'

services:
 
  db:
    container_name: db
    image: mysql:5.7.24
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: 'smfony'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: ''
    volumes:
        - ./db:/var/lib/mysql

  app:
    container_name: sf.app
    build: .docker/php
    volumes:
      - .:/app
      - ./var/logs:/app/var/logs
      - ./var/cache.:/app/var/cache

  nginx:
    container_name: sf.nginx
    build: .docker/nginx
    volumes_from:
      - app
    ports:
      - "81:80"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
        - PMA_HOST=db
        - PMA_USER=root
        - PMA_PASSWORD=root
    ports:
        - "${PHPMYADMIN_PORT}:80"
    restart: always

  
